### PR TITLE
Winsorized normalization

### PR DESCRIPTION
**Pull request by karoaper**

### CODE REVIEW

**Comment by twhnat** [comment]
I am having a lot of difficulty deciphering your pull request.  You should never merge other branches into your updates that you want pushed to the master branch.  These modifications were either already incorporated or were left in a branched state for a reason.  Can you undo these merges and update to the current master branch before resubmitting the pull request.  For the future, please keep a pull request confined to a single enhancement or bug.  This makes it easier to manage.

**Comment by karoaper** [comment]
Hi Tim,
Sorry about that.  
I'm working on it.
Thanks
-Karen

**Comment by twhnat** [comment]
Karen,
Can you take a look at these changes for correctness?  You should look at the current master branch.  I want to verify that they were merged correctly.

-twh

**Comment by karoaper** [comment]
Hey,
There was a bug in BinnedSratistics, but otherwise it looks good.
I made a pull request.
-Karen

**Pull request merged**
